name: 'Pixel 3a Kernel Build - Maximum Cleanup'
description: "Builds kernel with the most aggressive disk cleanup to prevent 'No space left' errors."
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  repo-token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: '1. Aggressive Disk Cleanup'
      shell: bash
      run: |
        echo "Initial free space:"
        df -h
        # Dọn dẹp các gói phần mềm lớn được cài sẵn
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/android
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/swift
        # Xóa các image Docker không sử dụng
        sudo docker image prune -af || true
        # Dọn dẹp cache của apt
        sudo apt-get clean
        echo "-------------------------------------------------"
        echo "Free space after aggressive cleanup:"
        df -h
        echo "-------------------------------------------------"

    - name: '2. Setup Environment & Dependencies'
      shell: bash
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y git build-essential zip curl libssl-dev bc device-tree-compiler python3 aria2
        # Giữ swap ở mức 8GB là hợp lý
        sudo fallocate -l 8G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile
        echo "Swap setup with 8GB."
        free -h

    - name: '3. Build Kernel (Serially)'
      shell: bash
      run: |
        set -e
        # Tải Toolchains và xóa file nén ngay lập tức
        echo "::group::Downloading Toolchains"
        mkdir -p "$HOME/clang" "$HOME/gcc-64" "$HOME/gcc-32"
        aria2c -x 16 -s 16 -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-release/clang-r383902.tar.gz && tar -C $HOME/clang -zxf aosp-clang.tar.gz && rm aosp-clang.tar.gz
        aria2c -x 16 -s 16 -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz && tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz && rm gcc-aarch64.tar.gz
        aria2c -x 16 -s 16 -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz && tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz && rm gcc-arm.tar.gz
        export PATH="$HOME/clang/bin:$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH"
        echo "::endgroup::"
        
        # Clone đúng source và branch
        echo "::group::Cloning PixelExperience Kernel Source (eleven-plus branch)"
        git clone --depth=1 "https://github.com/PixelExperience-Devices/kernel_google_msm-4.9.git" -b "twelve" kernel_src
        cd kernel_src
        echo "::endgroup::"
        
        # Build Kernel với -j1 để đảm bảo không bị lỗi RAM
        echo "::group::Building Kernel (using -j1 for stability)"
        mkdir -p out
        make O=out ARCH=arm64 b1c1_defconfig
        make -j1 O=out ARCH=arm64 \
            CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- \
            CROSS_COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CC=clang \
            all
        echo "Build complete. Final disk space usage:"
        df -h
        echo "::endgroup::"

    - name: '4. Packaging & Upload'
      # Bước này không thay đổi vì nó đã đúng
      uses: actions/checkout@v3 # Cần checkout để dùng action khác
      with:
        path: 'temp_checkout' # Tránh ghi đè
    - uses: ./temp_checkout/.github/actions/package-and-upload # Gọi một action con
      id: package
      with:
        kernel_dir: 'kernel_src'

