name: 'Pixel 3a Kernel Build - Final Working Version'
description: "A simplified and corrected action based on a proven working example."
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  repo-token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Setup Environment & Dependencies'
      shell: bash
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y git ccache build-essential zip curl libssl-dev libxml2-utils bc device-tree-compiler python3 aria2
        aria2c -q https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh && NONINTERACTIVE=1 bash ./uninstall.sh -f -q || true
        sudo fallocate -l 16G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile

    - name: 'Build Kernel'
      shell: bash
      run: |
        set -e
        # 1. TẢI TOOLCHAINS (Clang + GCC)
        echo "::group::Downloading Toolchains"
        mkdir -p "$HOME/clang" "$HOME/gcc-64" "$HOME/gcc-32"
        aria2c -x 16 -s 16 -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-release/clang-r383902.tar.gz
        tar -C $HOME/clang -zxf aosp-clang.tar.gz
        aria2c -x 16 -s 16 -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz
        tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
        aria2c -x 16 -s 16 -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz
        tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
        export PATH="$HOME/clang/bin:$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH"
        echo "::endgroup::"
        
        # 2. CLONE ĐÚNG SOURCE VÀ BRANCH
        echo "::group::Cloning PixelExperience Kernel Source (eleven-plus branch)"
        KERNEL_URL="https://github.com/PixelExperience-Devices/kernel_google_msm-4.9.git"
        KERNEL_BRANCH="twelve"
        git clone --depth=1 "$KERNEL_URL" -b "$KERNEL_BRANCH" kernel_src
        cd kernel_src
        echo "✅ Cloned from $KERNEL_URL on branch $KERNEL_BRANCH"
        echo "::endgroup::"
        
        # 3. BUILD KERNEL VỚI LỆNH CHUNG
        echo "::group::Building Kernel"
        mkdir -p out
        make -j$(nproc) O=out ARCH=arm64 b1c1_defconfig
        make -j$(nproc) O=out ARCH=arm64 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CC=clang \
            all
        echo "::endgroup::"
        
        # 4. ĐÓNG GÓI VỚI LOGIC TÌM KIẾM LINH HOẠT
        echo "::group::Packaging AnyKernel3"
        cd .. # Quay lại thư mục gốc của workspace
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3
        
        # Logic sao chép y hệt action thành công
        if [ -f kernel_src/out/arch/arm64/boot/Image.*-dtb ]; then
            cp kernel_src/out/arch/arm64/boot/Image.*-dtb AnyKernel3/ -v
            echo "Copied Image.*-dtb"
        elif [ -f kernel_src/out/arch/arm64/boot/Image.* ]; then
            cp kernel_src/out/arch/arm64/boot/Image.* AnyKernel3/ -v
            echo "Copied Image.*"
        else
            cp kernel_src/out/arch/arm64/boot/Image AnyKernel3/ -v
            echo "Copied raw Image"
        fi
        
        # Sao chép dtbo.img nếu có
        test -f kernel_src/out/arch/arm64/boot/dtbo.img && cp -v kernel_src/out/arch/arm64/boot/dtbo.img AnyKernel3/
        
        # Cấu hình AnyKernel3
        cat > AnyKernel3/anykernel.sh <<'EOAKS'
# AnyKernel3 Ramdisk Mod Script
properties() {
kernel.string=Custom Kernel for Pixel 3a/3a XL by GitHub Actions
do.devicecheck=1; do.modules=0; do.systemless=1; do.cleanup=1; do.cleanuponabort=0;
device.name1=sargo; device.name2=bonito; supported.versions=10-13;
}
. tools/ak3-core.sh;
dump_boot;
kernel_image=$(find . -name "Image.*" | head -n 1);
if [ -n "$kernel_image" ]; then
  mv -f "$kernel_image" "$split_img/boot.img-kernel";
else
  ui_print " ! No kernel image found in zip";
  exit 1;
fi;
write_boot;
if [ -f dtbo.img ]; then
  flash_dtbo;
fi;
EOAKS
        
        # Tạo file zip
        cd AnyKernel3
        zip -r9 "../build-pixel3a-kernel.zip" ./*
        cd ..
        echo "✅ Flashable zip created: build-pixel3a-kernel.zip"
        echo "::endgroup::"
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: pixel3a-kernel-zip
        path: build-pixel3a-kernel.zip
