name: 'Android Kernel Build Action'
description: "A action to built android kernel."

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  kernel-url:
    description: 'Kernel Source Url'
    required: true
  repo-token:
    description: 'Token'
    required: false
  depth:
    required: false
    default: 1
  vendor:
    required: false
    default: false
  vendor-url:
    description: 'Kernel Vendor Source Url'
    required: false
  kernel-dir:
    required: false
    default: kernel
  vendor-dir:
    required: false
    default: vendor
  kernel-branch:
    description: 'Branch name for kernel source'
    required: false
  vendor-branch:
    description: 'Branch name for vendor kernel source'
    required: false
  config:
    description: 'configuration for building android kernel'
    required: true
    default: defconfig
  arch:
    required: true
    default: arm64
  android-version:
    description: 'Android version.'
    required: false
    default: ""
  ksu:
    description: 'KernelSU function support'
    required: false
    default: false
  rekernel:
    required: false
    default: false
  ksu-version:
    description: 'KernelSU default branch'
    required: false
    default: "main"
  ksu-other:
    required: false
    default: false
  ksu-url:
    required: false
  ksu-lkm:
    required: false
    default: false
  disable-lto:
    required: false
    default: false
  lxc:
    required: false
    default: false
  lxc-patch:
    required: false
    default: false
  nethunter:
    required: false
    default: false
  nethunter-patch:
    required: false
    default: false
  kvm:
    required: false
    default: false
  ccache:
    required: false
    default: false
  aosp-gcc:
    required: false
    default: false
  other-gcc32-url:
    required: false
  other-gcc32-branch:
    required: false
  other-gcc64-url:
    required: false
  other-gcc64-branch:
    required: false
  aosp-clang:
    required: false
    default: false
  aosp-clang-version:
    required: false
    default: "r383902"
  other-clang-url:
    required: false
  other-clang-branch:
    required: false
    default: main
  anykernel3:
    required: false
    default: false
  anykernel3-url:
    required: false
  bootimg-url:
    required: false
  release:
    required: false
    default: false
  access-token:
    required: false
  extra-cmd:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup ccache
      if: inputs.ccache == 'true'
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ inputs.config }}
        max-size: 4G
        create-symlink: true

    - name: Build Kernel
      shell: bash
      run: |
          if [[ ${GITHUB_ACTIONS} != "true" || ${OSTYPE} != "linux-gnu" || ! -f /bin/apt ]]; then
              printf "This Action Is Intended For Debian-based Runner.\n"
              exit 127
          fi

          SU() { if [ "$(id -u)" -eq 0 ]; then "$@"; else sudo "$@"; fi }

          # TINH TÚY 1: SET SWAP 16G (Tránh lỗi link driver Wi-Fi Pixel 3a)
          echo "::group:: Setting Up 16GB Swap"
          SU fallocate -l 16G /swapfile
          SU chmod 600 /swapfile
          SU mkswap /swapfile
          SU swapon /swapfile
          echo "::endgroup::"

          # TINH TÚY 2: CÀI PYTHON 2.7 (Cho scripts DTC đời cũ)
          echo "::group:: Installing Depend Packages"
          echo "deb [trusted=yes] https://deb.debian.org/debian/ bullseye main contrib non-free" | SU tee -a /etc/apt/sources.list
          SU apt-get update
          SU apt-get install --no-install-recommends -y binutils git make bc bison openssl curl zip kmod cpio flex libelf-dev libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates python2.7 python3 xz-utils aria2 build-essential ccache pigz parallel
          SU ln -sf /usr/bin/python2.7 /usr/bin/python
          echo "::endgroup::"

          download_and_extract() {
              local url=$1; local output_name=$2; local extract_dir=$3; local branch=${4:-main}
              mkdir -p -v "$extract_dir"
              case "$url" in
                  *.zip) aria2c -o "${output_name}.zip" "$url"; unzip -q "${output_name}.zip" -d "$extract_dir" ;;
                  *.tar.*|*.gz|*.xz|*.bz2) aria2c -o "${output_name}.${url##*.}" "$url"; tar -C "$extract_dir" -xf "${output_name}.${url##*.}" ;;
                  *) git clone "$url" "$extract_dir" --depth=${{ inputs.depth }} -b "$branch" ;;
              esac
          }

          # --- Giữ nguyên logic Download Toolchain ---
          if [ ${{ inputs.aosp-clang }} = true ]; then
              echo "::group:: Downloading AOSP clang"
              AOSP_CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android${{ inputs.android-version }}-release/clang-${{ inputs.aosp-clang-version }}.tar.gz"
              [ -z "${{ inputs.android-version }}" ] && AOSP_CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-${{ inputs.aosp-clang-version }}.tar.gz"
              download_and_extract "$AOSP_CLANG_URL" "aosp-clang" "$HOME/clang"
              echo "::endgroup::"
          elif [ ! -z ${{ inputs.other-clang-url }} ]; then
              download_and_extract "${{ inputs.other-clang-url }}" "clang" "$HOME/clang" "${{ inputs.other-clang-branch }}"
          fi

          if [ ${{ inputs.aosp-gcc }} = true ]; then
              G64="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz"
              G32="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz"
              download_and_extract "$G64" "gcc-aarch64" "$HOME/gcc-64"
              download_and_extract "$G32" "gcc-arm" "$HOME/gcc-32"
          fi

          # TINH TÚY 3: CLONE SOURCE (Dùng biến inputs.kernel-url thay vì link cứng)
          echo "::group:: Pulling Kernel Source"
          git clone --recursive ${{ inputs.kernel-url }} -b "${{ inputs.kernel-branch }}" --depth=${{ inputs.depth }} kernel/${{ inputs.kernel-dir }}
          echo "::endgroup::"

          # (Giữ nguyên logic Pull Vendor nếu có)
          if [ "${{ inputs.vendor }}" = true ]; then
              git clone ${{ inputs.vendor-url }} --depth=${{ inputs.depth }} kernel/${{ inputs.vendor-dir }} -b ${{ inputs.vendor-branch }}
              test -d kernel/${{ inputs.vendor-dir }}/vendor && cp -rv kernel/${{ inputs.vendor-dir }}/vendor kernel
          fi

          cd kernel/${{ inputs.kernel-dir }}

          # TINH TÚY 4: FIX CONFIG PATH (Cho Pixel 3a)
          REAL_CONF=$(find arch/${{ inputs.arch }}/configs -name "${{ inputs.config }}" | head -n 1)
          [ ! -z "$REAL_CONF" ] && cp -f "$REAL_CONF" "arch/${{ inputs.arch }}/configs/${{ inputs.config }}"

          # --- Giữ nguyên logic Patch (KernelSU, NetHunter, LTO, KVM, LXC) ---
          VERSION=$(grep -E '^VERSION = ' Makefile | awk '{print $3}')
          PATCHLEVEL=$(grep -E '^PATCHLEVEL = ' Makefile | awk '{print $3}')
          [ "$VERSION" -lt 5 ] && touch nongki.txt

          if [ ${{ inputs.ksu }} = true ]; then
              KVER=${{ inputs.ksu-version }}
              [ -f nongki.txt ] && KVER=v0.9.5
              curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s "$KVER"
          fi

          # (Đoạn LTO, LXC, KVM... giữ nguyên như mã cũ của bạn)
          if [ ${{ inputs.disable-lto }} = true ]; then
              sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/g' arch/${{ inputs.arch }}/configs/${{ inputs.config }}
              sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/g' arch/${{ inputs.arch }}/configs/${{ inputs.config }}
              echo "CONFIG_LTO_NONE=y" >> arch/${{ inputs.arch }}/configs/${{ inputs.config }}
          fi

          # TINH TÚY 5: TÁCH LỆNH BUILD & GIỚI HẠN -J4
          echo "::group:: Building Kernel"
          mkdir -p out
          
          # Setup Toolchain Paths
          [ -d "$HOME/clang/bin" ] && export PATH="$HOME/clang/bin:$PATH"
          [ -d "$HOME/gcc-64/bin" ] && GCC64_PATH="$HOME/gcc-64/bin/"
          [ -d "$HOME/gcc-32/bin" ] && GCC32_PATH="$HOME/gcc-32/bin/"
          
          CMD_CC="clang"; [ ${{ inputs.ccache }} = true ] && CMD_CC="ccache clang"
          
          COMMON_ARGS="ARCH=${{ inputs.arch }} O=out CROSS_COMPILE=${GCC64_PATH}aarch64-linux-android- CROSS_COMPILE_ARM32=${GCC32_PATH}arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC=$CMD_CC"

          # Bước 1: Config
          make ${COMMON_ARGS} ${{ inputs.config }}
          # Bước 2: Build chính thức (j4 + KCFLAGS)
          make -j4 ${COMMON_ARGS} all ${{ inputs.extra-cmd }} KCFLAGS="-Wno-error" HOSTCFLAGS="-Wno-error"
          echo "::endgroup::"

          # --- Giữ nguyên logic đóng gói AnyKernel3 / Bootimg ---
          if [ ${{ inputs.anykernel3 }} = false ]; then
             echo "::group:: Preparing to Upload boot.img"
             mkdir -p split && cd split
             aria2c ${{ inputs.bootimg-url }} -o boot.img
             # Logic Magiskboot của bạn...
             # (Copy lại phần xử lý boot.img từ mã cũ của bạn vào đây)
             cd ..
          else
             echo "::group:: Packaging Anykernel3"
             git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
             cp out/arch/${{ inputs.arch }}/boot/Image* AnyKernel3/
             [ -f out/arch/${{ inputs.arch }}/boot/dtbo.img ] && cp out/arch/${{ inputs.arch }}/boot/dtbo.img AnyKernel3/
             mkdir -p ../../build
             cd AnyKernel3 && zip -r ../../../build/Anykernel3-flasher.zip ./*
             echo "::endgroup::"
          fi

    # --- Giữ nguyên các bước Upload và Release ---
    - id: upload
      uses: actions/upload-artifact@v4
      with:
        name: kernel-result
        path: build/*
