name: 'Pixel 3a Kernel Build - Stable & Final'
description: "Builds Pixel 3a kernel with aggressive disk cleanup and serialized jobs for stability."
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  repo-token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: '1. Free Up Disk Space on Runner'
      shell: bash
      run: |
        echo "Initial free space:"
        df -h
        sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/android
        sudo docker image prune -af || true
        sudo apt-get clean
        echo "Free space after cleanup:"
        df -h

    - name: '2. Setup Environment & Dependencies'
      shell: bash
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y git build-essential zip curl libssl-dev bc device-tree-compiler python3 aria2
        sudo fallocate -l 8G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile
        echo "Swap setup with 8GB."
        free -h

    - name: '3. Build Kernel (Serially)'
      shell: bash
      run: |
        set -e
        # Tải Toolchains
        echo "::group::Downloading Toolchains"
        mkdir -p "$HOME/clang" "$HOME/gcc-64" "$HOME/gcc-32"
        aria2c -x 16 -s 16 -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-release/clang-r383902.tar.gz && tar -C $HOME/clang -zxf aosp-clang.tar.gz && rm aosp-clang.tar.gz
        aria2c -x 16 -s 16 -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz && tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz && rm gcc-aarch64.tar.gz
        aria2c -x 16 -s 16 -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz && tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz && rm gcc-arm.tar.gz
        export PATH="$HOME/clang/bin:$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH"
        echo "::endgroup::"
        
        # Clone đúng source và branch
        echo "::group::Cloning PixelExperience Kernel Source (eleven-plus branch)"
        git clone --depth=1 "https://github.com/PixelExperience-Devices/kernel_google_msm-4.9.git" -b "twelve" kernel_src
        cd kernel_src
        echo "::endgroup::"
        
        # Build Kernel với lệnh chung
        echo "::group::Building Kernel"
        mkdir -p out
        make O=out ARCH=arm64 b1c1_defconfig
        
        # --- THAY ĐỔI QUAN TRỌNG NHẤT ĐỂ FIX LỖI HẾT RAM ---
        # Sử dụng -j1 để build tuần tự, tránh quá tải bộ nhớ
        make -j2 O=out ARCH=arm64 \
            CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- \
            CROSS_COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CC=clang \
            all
        echo "::endgroup::"

    - name: '4. Packaging AnyKernel3'
      # ... Toàn bộ bước này và bước sau giữ nguyên y hệt như cũ ...
      env:
        ANYKERNEL_SCRIPT: |
          # AnyKernel3 Ramdisk Mod Script
          properties() {
          kernel.string=Custom Kernel for Pixel 3a/3a XL by GitHub Actions
          do.devicecheck=1; do.modules=0; do.systemless=1; do.cleanup=1; do.cleanuponabort=0;
          device.name1=sargo; device.name2=bonito; supported.versions=10-13;
          }
          . tools/ak3-core.sh;
          dump_boot;
          kernel_image=$(find . -name "Image.*" | head -n 1);
          if [ -n "$kernel_image" ]; then
            mv -f "$kernel_image" "$split_img/boot.img-kernel";
          else
            ui_print " ! No kernel image found in zip";
            exit 1;
          fi;
          write_boot;
          if [ -f dtbo.img ]; then
            flash_dtbo;
          fi;
      shell: bash
      run: |
        set -e
        echo "::group::Packaging AnyKernel3"
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3
        if [ -f kernel_src/out/arch/arm64/boot/Image.*-dtb ]; then
            cp kernel_src/out/arch/arm64/boot/Image.*-dtb AnyKernel3/ -v
        elif [ -f kernel_src/out/arch/arm64/boot/Image.* ]; then
            cp kernel_src/out/arch/arm64/boot/Image.* AnyKernel3/ -v
        else
            cp kernel_src/out/arch/arm64/boot/Image AnyKernel3/ -v
        fi
        test -f kernel_src/out/arch/arm64/boot/dtbo.img && cp -v kernel_src/out/arch/arm64/boot/dtbo.img AnyKernel3/
        echo "$ANYKERNEL_SCRIPT" > AnyKernel3/anykernel.sh
        cd AnyKernel3
        zip -r9 "../build-pixel3a-kernel.zip" ./*
        cd ..
        echo "✅ Flashable zip created."
        echo "::endgroup::"
    
    - name: '5. Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: pixel3a-kernel-zip
        path: build-pixel3a-kernel.zip
