name: 'Android Kernel Build Action'
description: "Final Stable Build - Pixel 3a (DTB fixed)"

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  kernel-url:
    required: true
  repo-token:
    required: true
  kernel-branch:
    required: true
  config:
    required: true
  arch:
    default: arm64
  aosp-clang-version:
    default: "r383902"
  android-version:
    default: "11"
  anykernel3:
    default: "true"

runs:
  using: 'composite'
  steps:
    - name: Cleanup & Setup environment
      shell: bash
      run: |
        set -e
        SU() { [ "$(id -u)" -eq 0 ] && "$@" || sudo "$@"; }

        echo "::group:: Cleaning Runner"
        aria2c -q https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
        NONINTERACTIVE=1 bash ./uninstall.sh -f -q || true
        SU rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
        echo "::endgroup::"

        echo "::group:: Setting Up 16GB Swap"
        if [ -f /bin/swapon ]; then
          SU fallocate -l 16G /swapfile
          SU chmod 600 /swapfile
          SU mkswap /swapfile
          SU swapon /swapfile
        fi
        echo "::endgroup::"

        echo "::group:: Installing Dependencies"
        echo "deb [trusted=yes] https://deb.debian.org/debian/ bullseye main contrib non-free" | SU tee -a /etc/apt/sources.list
        SU apt-get update
        SU apt-get install --no-install-recommends -y \
          git make bc bison openssl curl zip kmod cpio flex \
          libelf-dev libssl-dev libc6-dev device-tree-compiler \
          python2.7 python3 xz-utils aria2 build-essential lz4
        SU ln -sf /usr/bin/python2.7 /usr/bin/python
        echo "::endgroup::"

    - name: Build Kernel
      shell: bash
      run: |
        set -e

        download_toolchain() {
          mkdir -p "$2"
          aria2c -x16 -s16 -o toolchain.tar.gz "$1"
          tar -xf toolchain.tar.gz -C "$2"
          rm -f toolchain.tar.gz
        }

        echo "::group:: Toolchains"
        download_toolchain \
          "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android${{ inputs.android-version }}-release/clang-${{ inputs.aosp-clang-version }}.tar.gz" \
          "$HOME/clang"
        download_toolchain \
          "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz" \
          "$HOME/gcc-64"
        download_toolchain \
          "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz" \
          "$HOME/gcc-32"
        echo "::endgroup::"

        export PATH="$HOME/clang/bin:$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH"

        echo "::group:: Clone Kernel"
        git clone --depth=1 "https://x-oauth-basic:${{ inputs.repo-token }}@$(echo ${{ inputs.kernel-url }} | sed 's|https://||')" \
          -b "${{ inputs.kernel-branch }}" kernel_src
        echo "::endgroup::"

        cd kernel_src

        echo "::group:: Config Fix"
        CONF="arch/${{ inputs.arch }}/configs/${{ inputs.config }}"
        sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/g' "$CONF"
        sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/g' "$CONF"
        echo "CONFIG_LTO_NONE=y" >> "$CONF"
        echo "::endgroup::"

        echo "::group:: Compile Kernel"
        mkdir -p out
        ARGS="ARCH=${{ inputs.arch }} O=out \
          CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- \
          CROSS_COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- \
          CC=clang LLVM=1 LLVM_IAS=1"

        make $ARGS ${{ inputs.config }}
        make -j3 $ARGS all
        echo "::endgroup::"

        echo "::group:: Build DTBs"
        make $ARGS dtbs
        echo "::endgroup::"

        echo "::group:: Create Image.lz4-dtb"
        BOOT_OUT=out/arch/${{ inputs.arch }}/boot
        DTB=$(find $BOOT_OUT/dts -name "*.dtb" | head -n 1)

        if [ ! -f "$BOOT_OUT/Image.lz4" ]; then
          lz4 -f $BOOT_OUT/Image $BOOT_OUT/Image.lz4
        fi

        cat $BOOT_OUT/Image.lz4 $DTB > $BOOT_OUT/Image.lz4-dtb
        ls -lh $BOOT_OUT/Image.lz4-dtb
        echo "::endgroup::"

        mkdir -p ../build
        cp $BOOT_OUT/Image.lz4-dtb ../build/

    - name: Packaging AnyKernel3
      if: inputs.anykernel3 == 'true'
      shell: bash
      run: |
        set -e
        git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
        cp kernel_src/out/arch/arm64/boot/Image.lz4-dtb AnyKernel3/

        AK=AnyKernel3/anykernel.sh
        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' $AK
        sed -i 's/is_slot_device=0;/is_slot_device=auto;/g' $AK
        echo "kernel.string=Image.lz4-dtb" >> $AK

        cd AnyKernel3
        zip -r9 ../pixel3a-kernel.zip .
        cd ..

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: pixel3a-kernel
        path: |
          build/Image.lz4-dtb
          pixel3a-kernel.zip
