name: 'Android Kernel Build Action - Pixel 3a Fixed'
description: "Complete build with DTB appending for Pixel 3a (sargo) - Fixed boot hang"

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  kernel-url:
    required: true
  repo-token:
    required: true
  kernel-branch:
    required: true
  config:
    required: true
  arch:
    default: arm64
  aosp-clang-version:
    default: "r383902"
  android-version:
    default: "11"
  anykernel3:
    default: "true"

runs:
  using: 'composite'
  steps:
    - name: Cleanup & Setup environment
      shell: bash
      run: |
          set -e
          SU() { [ "$(id -u)" -eq 0 ] && "$@" || sudo "$@"; }
          
          # 1. Gỡ Homebrew và dọn dẹp PATH để tránh xung đột
          echo "::group::Cleaning Runner"
          aria2c -q https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
          NONINTERACTIVE=1 bash ./uninstall.sh -f -q
          SU rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          echo "::endgroup::"

          # 2. Thiết lập Swap 16GB
          echo "::group::Setting Up 16GB Swap"
          if [ -f /bin/swapon ]; then
              export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
              [ ! -z "$SWAP_FILE" ] && SU swapoff $SWAP_FILE && SU rm -f $SWAP_FILE
              SU fallocate -l 16G /swapfile
              SU chmod 600 /swapfile
              SU mkswap /swapfile
              SU swapon /swapfile
          fi
          echo "::endgroup::"

          # 3. Cài đặt dependencies
          echo "::group::Installing Dependencies & mkdtimg"
          echo "deb [trusted=yes] https://deb.debian.org/debian/ bullseye main contrib non-free" | SU tee -a /etc/apt/sources.list
          SU apt-get update
          SU apt-get install --no-install-recommends -y binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi git make bc bison openssl curl zip kmod cpio flex libelf-dev libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates python2.7 python3 xz-utils aria2 build-essential ccache parallel
          
          wget -q https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/master/utils.tar.gz
          mkdir -p dtb-utils && tar -xvf utils.tar.gz -C dtb-utils
          SU cp dtb-utils/src/mkdtboimg.py /usr/bin/mkdtimg
          SU chmod +x /usr/bin/mkdtimg
          SU ln -sf /usr/bin/python2.7 /usr/bin/python
          echo "::endgroup::"

    - name: Build Kernel
      shell: bash
      run: |
        set -e
        SU() { [ "$(id -u)" -eq 0 ] && "$@" || sudo "$@"; }

        download_toolchain() {
            local url=$1; local name=$2; local dir=$3;
            mkdir -p "$dir"
            aria2c -x 16 -s 16 -k 1M -o "${name}.tar.gz" "$url"
            tar -C "$dir" -zxf "${name}.tar.gz"
            rm -f "${name}.tar.gz"
        }

        echo "::group::Downloading Toolchains"
        download_toolchain "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android${{ inputs.android-version }}-release/clang-${{ inputs.aosp-clang-version }}.tar.gz" "clang" "$HOME/clang"
        download_toolchain "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz" "gcc64" "$HOME/gcc-64"
        download_toolchain "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-13.0.0_r0.57.tar.gz" "gcc32" "$HOME/gcc-32"
        
        export PATH="$HOME/clang/bin:$HOME/gcc-64/bin:$HOME/gcc-32/bin:/usr/bin:/bin"
        echo "::endgroup::"

        echo "::group::Cloning Kernel Source"
        KURL=$(echo "${{ inputs.kernel-url }}" | sed 's|https://||')
        git clone --depth=1 "https://x-oauth-basic:${{ inputs.repo-token }}@$KURL" -b "${{ inputs.kernel-branch }}" kernel_src
        echo "::endgroup::"

        cd kernel_src
        
        echo "::group::Fixing Config"
        DEST_CONF="arch/${{ inputs.arch }}/configs/${{ inputs.config }}"
        REAL_CONF=$(find arch/${{ inputs.arch }}/configs -name "${{ inputs.config }}" | head -n 1)
        if [ -z "$REAL_CONF" ]; then 
            echo "❌ Config not found!"; 
            exit 1
        fi
        [ "$(realpath $REAL_CONF)" != "$(realpath $DEST_CONF)" ] && cp -f "$REAL_CONF" "$DEST_CONF"

        # Chỉ tắt LTO nếu cần thiết (comment dòng dưới nếu muốn giữ LTO)
        sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/g' "$DEST_CONF" || true
        sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/g' "$DEST_CONF" || true
        grep -q "CONFIG_LTO_NONE" "$DEST_CONF" || echo "CONFIG_LTO_NONE=y" >> "$DEST_CONF"
        
        # Đảm bảo DTB overlay được build
        grep -q "CONFIG_BUILD_ARM64_DT_OVERLAY" "$DEST_CONF" || echo "CONFIG_BUILD_ARM64_DT_OVERLAY=y" >> "$DEST_CONF"
        
        # Debug configs (optional, bỏ comment nếu cần debug boot)
        # echo "CONFIG_PRINTK=y" >> "$DEST_CONF"
        # echo "CONFIG_EARLY_PRINTK=y" >> "$DEST_CONF"
        
        echo "::endgroup::"

        echo "::group::Verify DTB Sources"
        # Kiểm tra device tree sources có tồn tại không
        echo "🔍 Checking for Device Tree sources..."
        
        if [ -d "arch/${{ inputs.arch }}/boot/dts/qcom" ]; then
            echo "✅ Found qcom DTS directory"
            
            # Tìm .dts files cho Pixel 3a
            DTS_COUNT=$(find arch/${{ inputs.arch }}/boot/dts/qcom -name "*sargo*.dts" -o -name "*bonito*.dts" -o -name "*sdm670*.dts" | wc -l)
            
            if [ $DTS_COUNT -gt 0 ]; then
                echo "✅ Found $DTS_COUNT device tree source files for Pixel 3a:"
                find arch/${{ inputs.arch }}/boot/dts/qcom -name "*sargo*.dts" -o -name "*bonito*.dts" -o -name "*sdm670*.dts" | head -5
            else
                echo "⚠️ WARNING: No specific sargo/bonito/sdm670 DTS files found!"
                echo "Available DTS files in qcom:"
                ls arch/${{ inputs.arch }}/boot/dts/qcom/*.dts 2>/dev/null | head -10
            fi
        else
            echo "❌ WARNING: qcom DTS directory not found!"
            echo "This kernel may not have Pixel 3a device trees"
        fi
        echo "::endgroup::"

        echo "::group::Compiling Kernel"
        mkdir -p out
        ARGS="ARCH=${{ inputs.arch }} O=out CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- CROSS_COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC=clang MKDTIMG=mkdtimg LLVM=1 LLVM_IAS=1"
        
        make $ARGS ${{ inputs.config }}
        
        # Thử build Image.lz4-dtb trực tiếp trước
        if make -j$(nproc) $ARGS Image.lz4-dtb dtbo.img KCFLAGS="-Wno-error" HOSTCFLAGS="-Wno-error" 2>/dev/null; then
            echo "✅ Image.lz4-dtb built successfully"
        else
            echo "⚠️ Image.lz4-dtb target not available, building separately..."
            make -j$(nproc) $ARGS Image.lz4 dtbs dtbo.img KCFLAGS="-Wno-error" HOSTCFLAGS="-Wno-error"
        fi
        echo "::endgroup::"

        echo "::group::Post-Build Processing"
        cd out/arch/arm64/boot
        
        # Tìm DTB file cho Pixel 3a (sargo)
        echo "🔍 Searching for DTB files..."
        DTB_FILE=""
        
        # Thử tìm các pattern phổ biến cho Pixel 3a
        for pattern in "*sargo*.dtb" "*bonito*.dtb" "*sdm670*.dtb" "sdm670-*.dtb"; do
            DTB_FILE=$(find dts -name "$pattern" 2>/dev/null | head -n 1)
            if [ -n "$DTB_FILE" ]; then
                echo "✅ Found DTB with pattern '$pattern': $DTB_FILE"
                break
            fi
        done
        
        # Nếu không tìm thấy, list tất cả và lấy bất kỳ DTB nào từ qcom
        if [ -z "$DTB_FILE" ]; then
            echo "⚠️ Specific sargo/bonito DTB not found, listing all available:"
            find dts -name "*.dtb" -exec ls -lh {} \;
            
            # Thử lấy bất kỳ DTB nào từ qcom (fallback)
            DTB_FILE=$(find dts/qcom -name "*.dtb" 2>/dev/null | head -n 1)
            
            if [ -n "$DTB_FILE" ]; then
                echo "⚠️ Using fallback DTB: $DTB_FILE"
            fi
        fi
        
        if [ -z "$DTB_FILE" ]; then
            echo "❌ CRITICAL: No DTB files found at all!"
            echo "Available DTS directory structure:"
            ls -R dts/ 2>/dev/null || echo "DTS directory not found!"
            
            echo ""
            echo "🔄 Attempting to download DTB from Google's stock kernel..."
            cd ../../../../
            
            # Download prebuilt DTB từ LineageOS hoặc Google
            STOCK_DTB_URL="https://github.com/LineageOS/android_kernel_google_bonito/raw/lineage-18.1/arch/arm64/boot/dts/qcom/sdm670-sargo-pvt-overlay.dtb"
            
            if curl -L -f -o stock-sargo.dtb "$STOCK_DTB_URL" 2>/dev/null; then
                echo "✅ Downloaded stock DTB successfully"
                mkdir -p out/arch/arm64/boot/dts/stock
                mv stock-sargo.dtb out/arch/arm64/boot/dts/stock/
                cd out/arch/arm64/boot
                DTB_FILE="dts/stock/stock-sargo.dtb"
                echo "✅ Using downloaded stock DTB: $DTB_FILE"
            else
                echo "❌ Failed to download stock DTB"
                echo ""
                echo "============================================"
                echo "CRITICAL ERROR: No DTB available!"
                echo "============================================"
                echo ""
                echo "Your kernel source does not have Device Tree files for Pixel 3a."
                echo "Please add device tree sources to your kernel or use a kernel"
                echo "that includes Pixel 3a (sargo/bonito) device trees."
                echo ""
                echo "You can get device trees from:"
                echo "  - https://github.com/LineageOS/android_kernel_google_bonito"
                echo "  - https://android.googlesource.com/kernel/msm/"
                echo ""
                exit 1
            fi
        fi
        
        # CRITICAL: Always check size and re-append if needed
        NEEDS_APPEND=0
        
        if [ -f Image.lz4-dtb ]; then
            SIZE_EXISTING=$(stat -c%s Image.lz4-dtb)
            SIZE_MB=$((SIZE_EXISTING / 1024 / 1024))
            echo "📦 Existing Image.lz4-dtb found: ${SIZE_MB}MB"
            
            # Nếu < 17MB thì chắc chắn thiếu DTB
            if [ $SIZE_EXISTING -lt 17000000 ]; then
                echo "⚠️ Size too small (${SIZE_MB}MB < 17MB), DTB missing!"
                NEEDS_APPEND=1
            else
                echo "✅ Size looks good (${SIZE_MB}MB), DTB likely present"
            fi
        else
            echo "📦 Image.lz4-dtb not found, will create it"
            NEEDS_APPEND=1
        fi
        
        # Append DTB nếu cần
        if [ $NEEDS_APPEND -eq 1 ]; then
            echo ""
            echo "🔨 Appending DTB to kernel..."
            
            if [ ! -f Image.lz4 ]; then
                echo "❌ Image.lz4 not found!"
                ls -lh
                exit 1
            fi
            
            SIZE_KERNEL=$(stat -c%s Image.lz4)
            SIZE_DTB=$(stat -c%s "$DTB_FILE")
            
            echo "📊 Image.lz4: $((SIZE_KERNEL / 1024 / 1024))MB"
            echo "📊 DTB file: $((SIZE_DTB / 1024))KB"
            echo "📊 DTB path: $DTB_FILE"
            
            # Backup nếu file cũ tồn tại
            [ -f Image.lz4-dtb ] && mv Image.lz4-dtb Image.lz4-dtb.old
            
            # Append DTB
            cat Image.lz4 "$DTB_FILE" > Image.lz4-dtb
            
            SIZE_FINAL=$(stat -c%s Image.lz4-dtb)
            SIZE_FINAL_MB=$((SIZE_FINAL / 1024 / 1024))
            
            echo ""
            echo "📦 FINAL: Image.lz4-dtb = ${SIZE_FINAL_MB}MB"
            
            # Verify append thành công
            if [ $SIZE_FINAL -le $SIZE_KERNEL ]; then
                echo "❌ CRITICAL ERROR: Append failed! Final size <= kernel size"
                echo "This means DTB was not appended!"
                exit 1
            fi
            
            if [ $SIZE_FINAL_MB -lt 17 ]; then
                echo "❌ CRITICAL ERROR: Final size ${SIZE_FINAL_MB}MB < 17MB"
                echo "DTB append may have failed or DTB file is invalid"
                echo "Expected: 17-20MB, Got: ${SIZE_FINAL_MB}MB"
                exit 1
            fi
            
            echo "✅ SUCCESS: DTB appended successfully!"
        fi
        
        # Verify files
        echo ""
        echo "📁 Final build artifacts:"
        ls -lh Image.lz4-dtb dtbo.img 2>/dev/null || ls -lh
        
        # ABSOLUTE FINAL CHECK
        echo ""
        echo "🔍 FINAL VERIFICATION"
        echo "===================="
        
        FINAL_SIZE=$(stat -c%s Image.lz4-dtb)
        FINAL_MB=$((FINAL_SIZE / 1024 / 1024))
        
        echo "Image.lz4-dtb size: ${FINAL_MB}MB (${FINAL_SIZE} bytes)"
        
        if [ $FINAL_SIZE -lt 17000000 ]; then
            echo ""
            echo "❌❌❌ CRITICAL BUILD FAILURE ❌❌❌"
            echo "===================================="
            echo "Image.lz4-dtb is only ${FINAL_MB}MB!"
            echo "Expected: 17-20MB (with DTB appended)"
            echo "Got: ${FINAL_MB}MB (DTB is missing!)"
            echo ""
            echo "This kernel WILL NOT BOOT on Pixel 3a!"
            echo "It will hang at the boot logo."
            echo ""
            echo "Please check:"
            echo "  1. Device tree sources exist in kernel"
            echo "  2. DTB files were compiled"
            echo "  3. DTB append logic executed correctly"
            echo ""
            exit 1
        elif [ $FINAL_SIZE -gt 25000000 ]; then
            echo "⚠️ WARNING: Image unusually large (${FINAL_MB}MB > 25MB)"
            echo "This is uncommon but may be okay"
        else
            echo "✅✅✅ BUILD SUCCESS ✅✅✅"
            echo "======================="
            echo "Image.lz4-dtb: ${FINAL_MB}MB"
            echo "DTB: PRESENT ✓"
            echo "Size: CORRECT ✓"
            echo ""
            echo "This kernel should boot successfully!"
        fi
        
        cd ../../../../
        echo "::endgroup::"

    - name: Packaging AnyKernel3
      shell: bash
      run: |
        set -e
        KERNEL_OUT="kernel_src/out/arch/${{ inputs.arch }}/boot"
        ZIP_OUT="build-pixel3a-kernel.zip"

        echo "::group::Clone AnyKernel3"
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3 AnyKernel3
        echo "::endgroup::"

        echo "::group::Copying kernel files"
        
        # Priority: Image.lz4-dtb (kernel with DTB appended)
        if [ -f $KERNEL_OUT/Image.lz4-dtb ]; then
            cp $KERNEL_OUT/Image.lz4-dtb AnyKernel3/Image.lz4-dtb
            KERNEL_NAME="Image.lz4-dtb"
            SIZE=$(stat -c%s $KERNEL_OUT/Image.lz4-dtb)
            echo "✅ Using Image.lz4-dtb ($((SIZE / 1024 / 1024))MB)"
        elif [ -f $KERNEL_OUT/Image.gz-dtb ]; then
            cp $KERNEL_OUT/Image.gz-dtb AnyKernel3/Image.gz-dtb
            KERNEL_NAME="Image.gz-dtb"
            SIZE=$(stat -c%s $KERNEL_OUT/Image.gz-dtb)
            echo "✅ Using Image.gz-dtb ($((SIZE / 1024 / 1024))MB)"
        else
            echo "❌ No kernel-dtb image found!"
            echo "Available files in $KERNEL_OUT:"
            ls -lah $KERNEL_OUT/
            exit 1
        fi

        # Copy DTBO
        if [ -f $KERNEL_OUT/dtbo.img ]; then
            cp $KERNEL_OUT/dtbo.img AnyKernel3/
            echo "✅ DTBO copied"
        else
            echo "⚠️ Warning: dtbo.img not found"
        fi
        
        echo "::endgroup::"

        echo "::group::Configuring AnyKernel3"
        cat > AnyKernel3/anykernel.sh <<'EOAKS'
        # AnyKernel3 Ramdisk Mod Script
        # osm0sis @ xda-developers
        
        properties() {
        kernel.string=Custom Kernel for Pixel 3a
        do.devicecheck=1
        do.modules=0
        do.systemless=1
        do.cleanup=1
        do.cleanuponabort=0
        device.name1=sargo
        device.name2=bonito
        supported.versions=10-13
        }
        
        . tools/ak3-core.sh
        
        dump_boot
        
        if [ -f Image.lz4-dtb ]; then
            mv -f Image.lz4-dtb $split_img/boot.img-kernel
        elif [ -f Image.gz-dtb ]; then
            mv -f Image.gz-dtb $split_img/boot.img-kernel
        fi
        
        write_boot
        flash_dtbo
        EOAKS
        chmod +x AnyKernel3/anykernel.sh
        echo "::endgroup::"

        echo "::group::Creating flashable ZIP"
        cd AnyKernel3
        zip -r9 "../$ZIP_OUT" ./*
        cd ..
        
        FINAL_SIZE=$(stat -c%s "$ZIP_OUT")
        echo "✅ Flashable zip created: $ZIP_OUT"
        echo "📦 Size: $((FINAL_SIZE / 1024 / 1024))MB"
        echo "::endgroup::"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pixel3a-kernel-dtb-fixed
        path: build-pixel3a-kernel.zip

    - name: Build Summary
      shell: bash
      run: |
        echo "## 🎉 Pixel 3a Kernel Build Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📦 Build Information" >> $GITHUB_STEP_SUMMARY
        
        if [ -f kernel_src/out/arch/arm64/boot/Image.lz4-dtb ]; then
            SIZE=$(stat -c%s kernel_src/out/arch/arm64/boot/Image.lz4-dtb)
            echo "- **Kernel Image**: Image.lz4-dtb" >> $GITHUB_STEP_SUMMARY
            echo "- **Size**: $((SIZE / 1024 / 1024))MB" >> $GITHUB_STEP_SUMMARY
            
            if [ $SIZE -ge 17000000 ]; then
                echo "- **Status**: ✅ DTB Successfully Appended" >> $GITHUB_STEP_SUMMARY
            else
                echo "- **Status**: ⚠️ DTB May Be Missing" >> $GITHUB_STEP_SUMMARY
            fi
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🚀 Flash Instructions" >> $GITHUB_STEP_SUMMARY
        echo "1. Download \`pixel3a-kernel-dtb-fixed\` artifact" >> $GITHUB_STEP_SUMMARY
        echo "2. Boot to TWRP recovery" >> $GITHUB_STEP_SUMMARY
        echo "3. Flash \`build-pixel3a-kernel.zip\`" >> $GITHUB_STEP_SUMMARY
        echo "4. Reboot system" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Device**: Pixel 3a (sargo/bonito)" >> $GITHUB_STEP_SUMMARY
