name: 'Pixel 3a Kernel Build - Correct Toolchain Sync'
description: "Builds kernel with fully synchronized toolchains for Android 12 to fix assembler errors."
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  repo-token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: '1. Aggressive Disk Cleanup & Setup'
      shell: bash
      run: |
        set -e
        echo "::group::Freeing up disk space"
        sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /usr/share/swift
        sudo docker image prune -af || true
        sudo apt-get clean
        df -h
        echo "::endgroup::"
        
        echo "::group::Installing Dependencies & Swap"
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y git build-essential zip curl libssl-dev bc device-tree-compiler python3 aria2
        sudo fallocate -l 8G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile
        echo "::endgroup::"

    - name: '2. Build Kernel with Synchronized Toolchains'
      shell: bash
      run: |
        set -e
        # --- PHẦN SỬA LỖI QUAN TRỌNG NHẤT ---
        echo "::group::Downloading SYNCHRONIZED Toolchains for Android 12"
        mkdir -p "$HOME/clang" "$HOME/gcc-64" "$HOME/gcc-32"
        # Tải Clang cho Android 12
        aria2c -x 16 -s 16 -o clang.tar.gz "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-release/clang-r383902b.tar.gz" && tar -C $HOME/clang -zxf clang.tar.gz && rm clang.tar.gz
        
        # Tải GCC cho Android 12 (KHÔNG phải Android 13)
        # Thay vì git clone, dùng URL archive để tải nhanh hơn
        aria2c -x 16 -s 16 -o gcc64.tar.gz "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android12-release.tar.gz" && tar -C $HOME/gcc-64 -zxf gcc64.tar.gz && rm gcc64.tar.gz
        aria2c -x 16 -s 16 -o gcc32.tar.gz "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android12-release.tar.gz" && tar -C $HOME/gcc-32 -zxf gcc32.tar.gz && rm gcc32.tar.gz
        
        export PATH="$HOME/clang/bin:$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH"
        echo "Toolchains are now synchronized."
        echo "::endgroup::"
        
        # Clone đúng source và branch
        echo "::group::Cloning PixelExperience Kernel Source"
        git clone --depth=1 "https://github.com/PixelExperience-Devices/kernel_google_msm-4.9.git" -b "twelve" kernel_src
        cd kernel_src
        echo "::endgroup::"
        
        # Build Kernel với -j1 để đảm bảo ổn định
        echo "::group::Building Kernel (using -j1 for stability)"
        mkdir -p out
        make O=out ARCH=arm64 b1c1_defconfig
        make -j1 O=out ARCH=arm64 \
            CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- \
            CROSS_COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CC=clang \
            all
        echo "::endgroup::"

    - name: '3. Package AnyKernel3 & Upload'
      env:
        ANYKERNEL_SCRIPT: |
          properties() {
          kernel.string=Custom Kernel for Pixel 3a/3a XL by vxd303
          do.devicecheck=1; do.modules=0; do.systemless=1; do.cleanup=1; do.cleanuponabort=0;
          device.name1=sargo; device.name2=bonito; supported.versions=10-13;
          }
          . tools/ak3-core.sh;
          dump_boot;
          kernel_image=$(find . -name "Image.*" | head -n 1);
          if [ -n "$kernel_image" ]; then
            mv -f "$kernel_image" "$split_img/boot.img-kernel";
          else
            ui_print " ! No kernel image found in zip";
            exit 1;
          fi;
          write_boot;
          if [ -f dtbo.img ]; then
            flash_dtbo;
          fi;
      shell: bash
      run: |
        set -e
        echo "::group::Packaging AnyKernel3"
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3
        
        # Logic sao chép linh hoạt đã được chứng minh
        if [ -f kernel_src/out/arch/arm64/boot/Image.*-dtb ]; then
            cp kernel_src/out/arch/arm64/boot/Image.*-dtb AnyKernel3/ -v
        elif [ -f kernel_src/out/arch/arm64/boot/Image.lz4 ]; then
            cp kernel_src/out/arch/arm64/boot/Image.lz4 AnyKernel3/ -v
        elif [ -f kernel_src/out/arch/arm64/boot/Image.gz ]; then
            cp kernel_src/out/arch/arm64/boot/Image.gz AnyKernel3/ -v
        else
            cp kernel_src/out/arch/arm64/boot/Image AnyKernel3/ -v
        fi
        
        test -f kernel_src/out/arch/arm64/boot/dtbo.img && cp -v kernel_src/out/arch/arm64/boot/dtbo.img AnyKernel3/
        
        echo "$ANYKERNEL_SCRIPT" > AnyKernel3/anykernel.sh
        
        cd AnyKernel3
        zip -r9 "../build-pixel3a-kernel.zip" ./*
        cd ..
        echo "✅ Flashable zip created."
        echo "::endgroup::"
    
    - name: '4. Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: pixel3a-kernel-zip
        path: build-pixel3a-kernel.zip
