name: 'Android Kernel Build Action'
description: "Final Optimized Action with CP Fix"

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  kernel-url:
    description: 'Kernel Source Url'
    required: true
  repo-token:
    description: 'GitHub PAT Token'
    required: false
  kernel-branch:
    description: 'Branch name'
    required: true
  config:
    description: 'configuration'
    required: true
  arch:
    default: arm64
  aosp-gcc:
    default: true
  aosp-clang:
    default: true
  aosp-clang-version:
    default: "r383902"
  android-version:
    default: "11"
  anykernel3:
    default: true

runs:
  using: 'composite'
  steps:
    - name: Cleanup Disk Space
      shell: bash
      run: |
          echo "::group:: Cleaning up Runner Disk Space"
          SU() { [ "$(id -u)" -eq 0 ] && "$@" || sudo "$@"; }
          SU rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          SU docker image prune -a -f
          echo "::endgroup::"

    - name: Build Kernel
      shell: bash
      run: |
          set -e
          SU() { [ "$(id -u)" -eq 0 ] && "$@" || sudo "$@"; }

          # 1. Setup 8GB Swap
          SU fallocate -l 8G /swapfile
          SU chmod 600 /swapfile
          SU mkswap /swapfile
          SU swapon /swapfile

          # 2. Cài đặt Python 2.7 & Dependencies
          echo "::group:: Installing Dependencies"
          echo "deb [trusted=yes] https://deb.debian.org/debian/ bullseye main contrib non-free" | SU tee -a /etc/apt/sources.list
          SU apt-get update
          SU apt-get install --no-install-recommends -y binutils git make bc bison openssl curl zip kmod cpio flex libelf-dev libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates python2.7 python3 xz-utils aria2 build-essential ccache parallel
          SU ln -sf /usr/bin/python2.7 /usr/bin/python
          echo "::endgroup::"

          # 3. Tải Toolchains
          download_toolchain() {
              local url=$1; local name=$2; local dir=$3;
              mkdir -p "$dir"
              aria2c -x 16 -s 16 -k 1M -o "${name}.tar.gz" "$url"
              tar -C "$dir" -zxf "${name}.tar.gz"
              rm -f "${name}.tar.gz"
          }

          if [ "${{ inputs.aosp-clang }}" = "true" ]; then
              echo "::group:: Downloading Clang"
              CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android${{ inputs.android-version }}-release/clang-${{ inputs.aosp-clang-version }}.tar.gz"
              [ -z "${{ inputs.android-version }}" ] && CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-${{ inputs.aosp-clang-version }}.tar.gz"
              download_toolchain "$CLANG_URL" "clang" "$HOME/clang"
              export PATH="$HOME/clang/bin:$PATH"
              echo "::endgroup::"
          fi

          if [ "${{ inputs.aosp-gcc }}" = "true" ]; then
              echo "::group:: Downloading GCC"
              GCC64_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz"
              GCC32_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz"
              download_toolchain "$GCC64_URL" "gcc64" "$HOME/gcc-64"
              download_toolchain "$GCC32_URL" "gcc32" "$HOME/gcc-32"
              export PATH="$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH"
              echo "::endgroup::"
          fi

          # 4. Clone Source
          echo "::group:: Cloning Kernel Source"
          KERNEL_URL="${{ inputs.kernel-url }}"
          if [ ! -z "${{ inputs.repo-token }}" ]; then
              KERNEL_URL=$(echo $KERNEL_URL | sed "s|https://|https://x-oauth-basic:${{ inputs.repo-token }}@|")
          fi
          git clone "$KERNEL_URL" -b "${{ inputs.kernel-branch }}" --depth=1 kernel_src
          cd kernel_src
          echo "::endgroup::"

          # 5. Build
          echo "::group:: Building"
          # SỬA LỖI CP TẠI ĐÂY: Chỉ copy nếu đường dẫn khác nhau
          DEST_CONF="arch/${{ inputs.arch }}/configs/${{ inputs.config }}"
          REAL_CONF=$(find arch/${{ inputs.arch }}/configs -name "${{ inputs.config }}" | head -n 1)
          
          if [ -z "$REAL_CONF" ]; then
              echo "❌ Config ${{ inputs.config }} not found!"
              exit 1
          fi

          if [ "$REAL_CONF" != "$DEST_CONF" ]; then
              echo "Copying config from $REAL_CONF to $DEST_CONF"
              cp -f "$REAL_CONF" "$DEST_CONF"
          else
              echo "Config is already in the correct location."
          fi

          mkdir -p out
          ARGS="ARCH=${{ inputs.arch }} O=out CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC=clang"
          
          make $ARGS ${{ inputs.config }}
          make -j4 $ARGS all KCFLAGS="-Wno-error" HOSTCFLAGS="-Wno-error"
          echo "::endgroup::"

          # 6. Packaging
          if [ "${{ inputs.anykernel3 }}" = "true" ]; then
              echo "::group:: Packaging"
              cd ..
              git clone https://github.com/osm0sis/AnyKernel3 --depth=1 AnyKernel3
              cp kernel_src/out/arch/${{ inputs.arch }}/boot/Image* AnyKernel3/
              [ -f kernel_src/out/arch/${{ inputs.arch }}/boot/dtbo.img ] && cp kernel_src/out/arch/${{ inputs.arch }}/boot/dtbo.img AnyKernel3/
              cd AnyKernel3 && zip -r ../build.zip ./*
              echo "::endgroup::"
          fi

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: kernel-${{ inputs.config }}
        path: build.zip
